### ISSUE TITLE
Issue with danish krowns kr.

### ISSUE THREAD

**Issue by PabloRuizCuevas** [fmaclen/svelte-currency-input#43]
When using <CurrencyInput name="total" value={10000} locale="da-DK" currency="DKK" /> 

the number formats like:

`100.000 kr.`

The problem is that the kr. is writable and deletable, so when you want to change the input you need fist to delete kr, I expect it to be jumped off by the cursor.

I don't mind to help solving this issue, but i think i will need a bit of orientation on how to do it.

**Comment by fmaclen** [comment]
@PabloRuizCuevas what's the locale and currency you are using?
