### ISSUE TITLE
Apply formatting of cents `on:blur` when the value doesn't have any cents

### ISSUE THREAD

**Issue by irt-msummers** [fmaclen/svelte-currency-input#52]
If you just enter a whole number or just to the tenths -- it leaves it without formatting it with the cents.  I did it really kludgey by 
 let fd=0
const setF = () => {
        fd=2
        setFormattedValue()
        fd=0
    }

and changed 
formattedValue = isZero ? '' : formatCurrency(value, fractionDigits, fd);

and then [
(on:blur={setF})

I am sure there is a better way

**Comment by fmaclen** [comment]
@irt-msummers I don't understand what you mean, can you record a short video of what the issue is?

**Comment by fmaclen** [comment]
Perfect, thanks for the clarification.
I'll take a closer look.

**Comment by fmaclen** [comment]
@irt-msummers I pushed #53 with the change you requested, can you check if that this fixes your use-case?
