### ISSUE TITLE
Multiple commas or periods

### ISSUE THREAD

**Issue by irt-msummers** [fmaclen/svelte-currency-input#55]
Is there someway to trap entering extra periods or commas -- they get switched but still display.  Just tested minus and it just repeats as well (not in video)

https://github.com/fmaclen/svelte-currency-input/assets/1631628/7a6b1266-d01c-4299-8554-f110cf45d6e6

**Comment by fmaclen** [comment]
@irt-msummers Can you post the props you are passing to the component? default value, locale, currency, etc...

**Comment by fmaclen** [comment]
Never mind, I was able to replicate the issue.
