### ISSUE TITLE
SvelteKit Import Error

### ISSUE THREAD

**Issue by rac146** [fmaclen/svelte-currency-input#68]
Ever since the 0.11 versions, I've been getting the following error when importing into my SvelteKit application:

![image](https://github.com/fmaclen/svelte-currency-input/assets/6462376/1e4443ac-127c-4537-93b7-07be7326e7ee)

I can safely ignore the error and application will still compile, but curious why this is popping up with 0.11 and not any of the previous versions..

**Comment by fmaclen** [comment]
I was able to replicate the error. I'll try to push a fix soon.

**Comment by fmaclen** [comment]
> but curious why this is popping up with 0.11 and not any of the previous versions..

@rac146 a few weeks ago I did some maintenance on the package/release workflow and I messed up the configuration, and this is not covered by any tests so it flew under the radar.

Should work be fixed in `0.11.2`. Let me know if the issue still persists or something else is wrong.
Thanks for reporting it!

**Comment by rac146** [comment]
Thanks for fixing!

Something is still weird though.. now when trying to install 0.11.2, this is happening:

<img width="610" alt="image" src="https://github.com/fmaclen/svelte-currency-input/assets/6462376/b1badce4-6740-412f-a8aa-40e9691c158c">

0.11.1 and other versions install correctly with svelte ^4.2.0

**Comment by fmaclen** [comment]
Oh, I see. I tested it on a project using Svelte 3.x and this didn't come up, but I do see this being an issue in projects with Svelte 4.x.

Can you try the following?

Open `/node_modules/@canutin/svelte-currency-input/package.json` and remove:
```json
"peerDependencies": {
  "svelte": "^3.5.9"
},
```

Then try `npm i` again and let me know if the error goes away.

**Comment by fmaclen** [comment]
For anyone having this problem in the future `0.11.3` should have fixed the issue, if it didn't please reply to this issue.
