### ISSUE TITLE
Change virtual keyboard behavior on Mobile (iOS)

### ISSUE THREAD

**Issue by pxd5295** [fmaclen/svelte-currency-input#69]
## Description
Currently on mobile when you select the currency input box you are presented with the standard "tel" virtual keyboard [1-9]. This makes it impossible to use decimal points to specify cent values. If we allowed for an option to set the underlying formatted input's  "inputmode" (https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode) we could allow devs to select between "decimal" and "numeric" keyboards on mobile.

## Version Used

0.11.1

**Comment by pxd5295** [comment]
@fmaclen Works perfect for me on iOS 16.6

Thanks for the quick help

**Comment by fmaclen** [comment]
@pxd5295 thanks for checking it out.
