### ISSUE TITLE
Input not reformatting after value changes 

### ISSUE THREAD

**Issue by irt-msummers** [fmaclen/svelte-currency-input#74]
## Description
If a value is changed programmatically the formattedValue doesn't refresh with fractionDigits. The $ is there but not the fractionDigits.

## Version Used

0.11.3

## Expected Behavior

It should show the fractionalDigits

## Actual Behavior

It shows the fractional digits the first time and on a value that is a whole number but if you change to another whole number it doesn't show them.  If you focus in and out of the inputbox it changes like it should.  

## Props Used

List down the props you used with the component, for example:

```svelte
<CurrencyInput name="default" bind:value={formState.AskPrice} />
```

## Reproduction Steps
I took your demo and just added a button click

https://svelte.dev/repl/20a823b0befe40ceb3fd3c4bd0b02bcb?version=4.2.10

1. Click change price in the example 
2. If you leave the number the same it still shows it with the decimal places. As a test, I set askPrice to 22 and change it to 22 it still shows $22.00 
3.

## Additional Info

- OS & Version:
- Browser & Version:
- Any other relevant details or potential solutions:

**Comment by irt-msummers** [comment]
IDK if this fixes it or what it might break

```
$:
      value, setFormattedValue(**true**);
```

Which is used here:
`  formattedValue = isZero && !isZeroNullish ? "" : formatCurrency(value, fractionDigits, hasMinFractionDigits ? fractionDigits : 0);`

**Comment by fmaclen** [comment]
Thanks for reporting this issue, I'll look into it.

**Comment by irt-msummers** [comment]
Thanks -- the only way I have been able to get around it is outside the component using `#key`

https://svelte.dev/repl/20a823b0befe40ceb3fd3c4bd0b02bcb?version=4.2.10

**Comment by irt-msummers** [comment]
Yes that seems to fix it on my application.  Thank you so much!!!!

**Comment by fmaclen** [comment]
@irt-msummers no problem, thank you!

**Comment by irt-msummers** [comment]
The way you changed it to using bind:this and switch it to format the input only if they are not typing was great idea.  Much better than the way I was using key to destroy/recreate it.
