### ISSUE TITLE
Allow adding an id

### ISSUE THREAD

**Issue by mleister97** [fmaclen/svelte-currency-input#79]
Please allow adding an id and all other props to the component and spread them. i want to link with a label to the input (this does required an id)

**Comment by fmaclen** [comment]
@mleister97 I'm onboard with adding an `id` property to the `input` but I'm a bit wary about allowing the spread of any random props.

What other props besides `id` do you need to spread?

**Comment by fmaclen** [comment]
@mleister97 here's a demo of the `id` prop (applied to the first field in the list):
https://79-id-prop.svelte-currency-input.pages.dev/

```svelte
<CurrencyInput name="default" value={-42069.69} id="four-twenty-six-nine" />
```

**Comment by mleister97** [comment]
Thanks for the quick response. I'm familiar with spreading all remaining props onto a built-in component like an input from React. I'm mainly a React user, and in many use cases, this makes sense when you want to use other built-in props.

E.g. any prop listet here
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by fmaclen** [comment]
I understood what you meant. The reason why we haven't allowed spreading of _any valid_ `<input>` attributes is most of them won't really have any effect (i.e. `step`, `popovertarget`, `checked`, etc) or may break the functionality (i.e `pattern`, `maxlength`).

The idea is is to explicitly declare those that are safe to use and document them properly in the README.md.
In this case `id` wouldn't break the functionality and it's a wise addition 👍 

So if we are missing other attributes that do make sense, I'm all ears.
