### ISSUE TITLE
Currency Input Not Submitting Form on Enter Key

### ISSUE THREAD

**Issue by mleister97** [fmaclen/svelte-currency-input#81]
Normally, forms are submitted when the Enter key is pressed in an input field. This is currently the case in my setup. However, when using a currency input, the form does not submit automatically when Enter is pressed. For accessibility reasons, I believe this functionality should be added here as well, or at least an option to enable it.

Enter does not work:

```
<form on:submit|preventDefault={handleSubmit}>
  <label for="input">Label</label>
  <CurrencyInput  id="input" name="input" required bind:value={einkommen} locale="de-AT" currency="EUR" />
  <button type="submit" class="col-span-2 md:col-span-1 md:col-start-2 kalk-button">Berechnen</button>
</form>
```

Enter does work:

```
<form on:submit|preventDefault={handleSubmit}>
  <label for="input">Label</label>
  <input id="input" name="input" required />
  <button type="submit" class="col-span-2 md:col-span-1 md:col-start-2 kalk-button">Berechnen</button>
</form>
```

**Comment by fmaclen** [comment]
@mleister97 This PR should address your use case: #82 

You can check out the demo:
https://submit-on-enter.svelte-currency-input.pages.dev/

If you focus on any `input` in that page and press `Enter` it should "submit the form" which reveals the payload example below.

**Comment by mleister97** [comment]
@fmaclen Looks perfectly fine
